#!/bin/bash


SCRIPT_DIR="/opt/iam-ssh"

[[ $(id -u) -gt 0 ]] && echo "must be root to execute this script" && exit 1

[[ "$1" == "" ]] && echo "Missing required configfile parameter" && exit 1
source $1

mkdir -p $SCRIPT_DIR
cp ./* $SCRIPT_DIR 

chown -R root:root $SCRIPT_DIR/*

$SCRIPT_DIR/configure_selinux.sh

# setup cronjob
IMPORT_USERS_FILE="$SCRIPT_DIR/import_users.sh"
CRON_D_CONFIG_FILE="/etc/cron.d/import_users"

if ! [ -f $CRON_D_CONFIG_FILE ]; then

cat > $CRON_D_CONFIG_FILE << EOF
SHELL=/bin/bash
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin
MAILTO=root
HOME=/
*/10 * * * * root $IMPORT_USERS_FILE $SCRIPT_DIR/aws-ec2-iam-ssh.conf
EOF

	chmod 0644 $CRON_D_CONFIG_FILE

else
	echo "File $CRON_D_CONFIG_FILE already exists. Skipping..."
fi

# setup sshd config
# see https://man.openbsd.org/sshd_config#AuthorizedKeysCommand

SSHD_CONFIG_FILE="/etc/ssh/sshd_config"
COMMAND_FILE="$SCRIPT_DIR/authorized_keys_command.sh"
SSHD_COMMAND_USER="root"

chown root:root $COMMAND_FILE
chmod 711 $COMMAND_FILE


# If this config already exists, comment it out

if grep -q "^AuthorizedKeysCommand $COMMAND_FILE" ${SSHD_CONFIG_FILE}; then
	sed -e '/AuthorizedKeysCommand / s/^#*/#/' -i $SSHD_CONFIG_FILE; 
fi

if grep -q "^AuthorizedKeysCommandUser $SSHD_COMMAND_USER" $SSHD_CONFIG_FILE; then
	sed -e '/AuthorizedKeysCommandUser / s/^#*/#/' -i $SSHD_CONFIG_FILE;
fi

cat >> $SSHD_CONFIG_FILE << EOF

#####################################################
# The following is generated by iam-ssh integration #
#####################################################

Match Group $LOCAL_GROUP_NAME
    AuthorizedKeysCommand $COMMAND_FILE
    AuthorizedKeysCommandUser $SSHD_COMMAND_USER

#####################################################

EOF

systemctl restart sshd.service

echo "Initializing iam users"
source $SCRIPT_DIR/import_users.sh $SCRIPT_DIR/aws-ec2-iam-ssh.conf